---
title: "Phytoplankton & zooplankton dilution experiments"
author: "Nick Baetge"
date: "compiled most recently on `r format(Sys.time(), '%d %B, %Y')`"
output: github_document

knit: (function(inputFile, encoding) {
      out_dir <- "../knitted";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})
---

```{r load packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(hms)
library(lubridate)
library(purrr)
library(patchwork)
library(janitor)
library(FactoMineR)
library(factoextra)
library(corrr)
library(ggcorrplot)
```

```{r define path to save data}
prod_path <-
  "/Users/nicholasbaetge/github/oceprf_smokeonthewater/prod/p6_dilution_exps.csv"
bcodmo_path <-
  "/Users/nicholasbaetge/github/oceprf_smokeonthewater/prod/bco_dmo/PHYTO_DILUTION.csv"
```

# Influx flow cytometry data

## Import and tidy data

```{r define paths to fcm data}
influx_path <-
  "/Users/nicholasbaetge/github/oceprf_smokeonthewater/raw/r6_phyto.xlsx"
# data contains cells in units of per L 
```

```{r import and id data, message = F}
ids <- readxl::read_xlsx(influx_path, sheet = 1) %>%
  select(exp, influx_id) %>% 
  distinct() 
```

```{r define paths to context data, message = F}
context_path <- "/Users/nicholasbaetge/github/oceprf_smokeonthewater/prod/p1_insitu_index.csv"

context <- read_csv(context_path) %>% 
  select(stn, exp, lat, lon, date, cluster, composite_z, chl_ap676lh:pico_syn)
```


```{r leachate data, message = F}
leach_nuts <- read_csv("/Users/nicholasbaetge/github/oceprf_smokeonthewater/prod/p3_ash_leachate_nuts_tm_doc.csv") %>% filter(type == "bold(Amendment)") %>%  select(trt, analyte, val) %>% pivot_wider( id_cols = trt, names_from = analyte, values_from = val)

leach_cdom <- read_csv("/Users/nicholasbaetge/github/oceprf_smokeonthewater/prod/p3_ash_leachate_eems.csv") %>% pivot_wider( id_cols = trt, names_from = slope_parameter, values_from = slope) %>% rename(E2_E3 = 2, SR = 3)

nuts <- left_join(leach_nuts, leach_cdom) %>% 
  add_row(trt = "Control") %>% 
  mutate_at(c(2:17), ~replace_na(.,0)) 
```



```{r caluclate rates, message=F, warning = F}
apparent_gr  <- readxl::read_xlsx(influx_path, sheet = 2) %>%
  select(influx_id:nano_tf) %>%
  mutate(syn_100 = syn_t0[syn_dil == 1],
         pico_100 = pico_t0[pico_dil == 1],
         nano_100 = nano_t0[nano_dil == 1]) %>%
  group_by(influx_id, trt) %>%
  fill(c(syn_100:nano_100)) %>%
  select(-contains("dil")) %>%
  mutate(
    syn_d = 1 - (syn_t0 / syn_100),
    pico_d = 1 - (pico_t0 / pico_100),
    nano_d = 1 - (nano_t0 / nano_100),
    syn_k = log(syn_tf / syn_t0),
    pico_k = log(pico_tf / pico_t0),
    nano_k = log(nano_tf / nano_t0)
  ) %>%
  select(influx_id, trt, contains(c("_d", "_k"))) %>%
  ungroup()

tidy_rates <- apparent_gr %>%
  select(influx_id:syn_d, syn_k) %>%
  rename(d = syn_d,
         k = syn_k) %>%
  mutate(phyto = "syn", .after = "trt") %>%
  bind_rows(
    .,
    apparent_gr %>%
      select(influx_id:trt, pico_d, pico_k) %>%
      rename(d = pico_d,
             k = pico_k) %>%
      mutate(phyto = "pico", .after = "trt")
  ) %>%
  bind_rows(
    .,
    apparent_gr %>%
      select(influx_id:trt, nano_d, nano_k) %>%
      rename(d = nano_d,
             k = nano_k) %>%
      mutate(phyto = "nano", .after = "trt")
  ) 
  
lm_rates <-  tidy_rates %>% 
  group_by(influx_id, trt, phyto) %>% 
  do(broom::tidy(lmodel2::lmodel2(data = ., formula = k ~ d))) %>% 
  filter(method == "SMA", term == "Slope") %>% 
  ungroup() %>% 
  mutate(negative_slope = ifelse(estimate < 0, T, F)) %>% 
  select(influx_id, trt, phyto, estimate, negative_slope) %>%
  rename(slope = estimate) %>% 
  distinct() %>% 
  left_join(tidy_rates, .)
  

rates <- lm_rates %>% 
    group_by(influx_id, trt, phyto) %>% 
    mutate(
      g = ifelse(d != 0 & negative_slope  == F, (k - k[d == 0]) / d, NA),
      # theory_violated = ifelse(g < 0, T, F),
      theory_violated = ifelse(negative_slope  == F, F, negative_slope),
      g_corr = ifelse(theory_violated == T | g < 0, 0, g),
      ave_g = mean(g_corr, na.rm = T),
      sd_g = sd(g_corr, na.rm = T),
      mu = g_corr + k[d == 0],
      ave_mu = mean(mu, na.rm = T),
      sd_mu = sd(mu, na.rm = T),
      r = mu - g_corr,
      ave_r = mean(r, na.rm = T),
      sd_r = sd(r, na.rm = T)
  ) %>%
  ungroup() %>%
  left_join(ids, .) %>%
  left_join(., context) %>%
  mutate(trt2 = ifelse(trt == "CTL", "Control", "Ash leachate"),
         .after = trt) %>%
  mutate(
    trt = case_when(
      trt == "CTL" ~ "Control",
      trt == "TFA" ~ "Thomas Fire Ash",
      trt == "LTA" ~ "Low Temp. Ash",
      trt == "HTA" ~ "High Temp. Ash"
    ),
    phyto = case_when(
      phyto == "syn" ~ "italic(Synechococcus)",
      phyto == "pico" ~ "Picoeukaryotes",
      phyto == "nano" ~ "Nanoeukaryotes"
    )
  ) %>%
  select(exp:trt, trt2, everything()) %>% 
  # filter(negative_slope == F) %>% 
  select(stn:pico_syn, exp, trt:sd_r) 

```

```{r prepare data for statistics}
data4stats <- rates %>% 
  filter(theory_violated == F) %>% 
  select(exp, trt, trt2, cluster:pico_syn, phyto, ave_g, ave_mu, ave_r) %>% 
  distinct() %>% 
   left_join(., nuts) %>% 
  rename(grazing = ave_g, 
         phyto_mu = ave_mu,
         accum = ave_r) %>% 
  mutate(grazing = ifelse(is.na(grazing), mean(grazing, na.rm = T), grazing), 
            phyto_mu = ifelse(is.na(phyto_mu), mean(phyto_mu, na.rm = T), phyto_mu), 
            accum = ifelse(is.na(accum), mean(accum, na.rm = T), accum)) %>% 
   mutate_at(vars(cluster), as_factor) %>% 
   mutate(phyto = ifelse( phyto == "italic(Synechococcus)", "Synechococcus", phyto))
```

#bco-dmo 

```{r tidy data for bcodmo}
bcodmo <- rates %>% 
  select(stn, lat, lon, trt, phyto, ave_mu, sd_mu, ave_g, sd_g, ave_r, sd_r) %>% 
  mutate(phyto = ifelse( phyto == "italic(Synechococcus)", "Synechococcus", phyto)) %>% 
  distinct() %>% 
  arrange(stn, trt, phyto) %>% 
  rename(division = 6,
         sd_division = 7,
         grazing = 8,
         sd_grazing = 9,
         accumulation = 10,
         sd_accumulation = 11) %>% 
  left_join(., context %>% select(stn, date)) %>% 
  mutate(time = as_hms("13:00:00"),
         date = mdy(date),
         dt = ymd_hms(paste(date, time))) %>% 
  select(stn, lat, lon, dt, everything(), -date, -time)
```


# Plots

```{r custom theme for plots}
custom.theme <- theme(
  legend.position = "top",
  legend.title = element_text(size = 35),
  legend.key.size = unit(3, "cm"),
  legend.key.spacing.x = unit(0.75, "cm"),
  legend.text = element_text(size = 38),
  legend.box = "vertical",
  legend.margin = margin(),
  axis.title = element_text(size = 44, face = "bold"),
  axis.text = element_text(size = 38),
  panel.spacing.x = unit(0.5, "cm"),
  panel.spacing.y = unit(1, "cm"),
  strip.text.x = element_text(
    size = 35,
    color = "white",
    face = "bold"
  ),
  strip.text.y = element_text(
    size = 42,
    color = "white",
    face = "bold"
  ),
  strip.background = element_rect(
    color = "black",
    fill = alpha('black', 0.7),
    linewidth = 1.5,
    linetype = "solid"
  )
)

pal4 = c("#785EF0", "#DC267F","#FFB000", "#FE6100")
pal3 = c("#DC267F","#FFB000", "#FE6100")
pal2 = c("#0947EA","#92EA33")
shape2 = c(21, 24)
shape2a = c(16, 4)
shape3 = c(21, 24, 22)
plot_levels = c(
  "Control",
  "Ash leachate",
  "Thomas Fire Ash",
  "Low Temp. Ash",
  "High Temp. Ash",
  "DOC",
  "bold(Leachate)",
  "bold(Amendment)",
  "Low~biomass",
  "High~biomass",
  "Low biomass",
  "High biomass",
  "bold(Division~(d^-1))",
  "bold(Grazing~(d^-1))",
  "bold(Accumulation~(d^-1))",
  "P13",
  "PB16",
  "PB15",
  "P17",
  "P1.5",
  "P12",
  "PB1",
  "PB14",
  "PB2",
  "PB3",
  "P2.5",
  "P4",
  "P3.5",
  "P5",
  "Synechococcus",
  "italic(Synechococcus)",
  "Picoeukaryotes",
  "Nanoeukaryotes"
)
```




```{r phyto mu model, fig.width=26, fig.asp = 0.6}
# Fit the ANOVA model with interaction
mod1 <- aov(phyto_mu ~ cluster * trt2, data = data4stats)

# Extract the ANOVA table
anova_results1 <- summary(mod1)

# Get p-values for significant terms
p_value_cluster <- anova_results1[[1]]["Pr(>F)"][1,1]
p_value_trt <- anova_results1[[1]]["Pr(>F)"][2,1]
# p_value_interaction <- anova_results2[[1]]["Pr(>F)"][3,1]

# Format p-values for annotations
formatted_p_cluster <- paste0("p = ", format.pval(p_value_cluster, digits = 2))
formatted_p_trt <- paste0("p = ", format.pval(p_value_trt, digits = 2))
# formatted_p_interaction <- paste0("p (cluster:trt) = ", format.pval(p_value_interaction, digits = 2))

cluster <- ggplot(data4stats, aes(x = factor(cluster, levels = plot_levels), y = phyto_mu, fill = cluster)) +
  geom_boxplot(alpha = 0.7,
    outlier.shape = NA,
    width = 0.4,
    position = position_dodge(0.5)) +
  geom_jitter(
    aes(fill = cluster, shape = phyto),
    size = 7,
    position = position_jitterdodge(jitter.width = 0.07, dodge.width = 0.7),
    alpha = 0.5, 
    stroke = 2,
    # shape = 21,
    color = "black"
  ) +
  labs(
    x = "SOM cluster",
    y = expression(bold(Division~rate~(d^-1))),
    fill = "",
    color = "",
    shape = ""
  ) +
  scale_fill_manual(values = pal2) +
  scale_color_manual(values = pal2) +
  scale_shape_manual(values = shape3) +
   theme_linedraw() +
  custom.theme +
  annotate(
    "text",
    x = 1,
    y = max(data4stats$phyto_mu, na.rm = TRUE),
    label = formatted_p_cluster,
    size = 6,  vjust = 2
  ) +
   guides(color = "none") 


# Plot for Treatment Effect with ANOVA p-value using Box Plot
trt <-  ggplot(data4stats, aes(x = factor(trt2, levels = plot_levels), y = phyto_mu, fill = factor(trt, levels = plot_levels))) +
  geom_boxplot(alpha = 0.7,
    outlier.shape = NA,
    width = 0.4,
    position = position_dodge(0.5)) +
  geom_jitter(
    aes(fill = factor(trt, levels = plot_levels), shape = phyto),
    size = 7,
    # shape = 21, 
    position = position_jitterdodge(jitter.width = 0.07, dodge.width = 0.7),
    alpha = 0.5,
    stroke = 2,
    color = "black"
  ) +
  labs(
    x = "Treatment",
    y = expression(bold(Division~rate~(d^-1))),
    fill = "",
    color = "",
    shape = ""
  ) +
  scale_fill_manual(values = pal4) +
  scale_color_manual(values = pal4) +
   scale_shape_manual(values = shape3) +
   theme_linedraw() +
  custom.theme +
  # Add p-value annotations for interaction
  annotate(
    "text",
    x = 1,
    y = max(data4stats$phyto_mu, na.rm = TRUE),
    label = formatted_p_trt,
    size = 6,  vjust = 2
  ) +
   guides(color= "none") 

# Combine plots side by side
mu <- cluster + trt +  plot_layout(guides = 'collect') & theme(legend.position = "top", legend.box="vertical", legend.margin=margin()) 

```


```{r grazing model, fig.width=26, fig.asp = 0.6}
# Fit the ANOVA model with interaction
mod2 <- aov(grazing ~ cluster * trt2, data = data4stats)

# Extract the ANOVA table
anova_results2 <- summary(mod2)

# Get p-values for significant terms
p_value_cluster <- anova_results2[[1]]["Pr(>F)"][1,1]
p_value_trt <- anova_results2[[1]]["Pr(>F)"][2,1]
p_value_interaction <- anova_results2[[1]]["Pr(>F)"][3,1]

# Format p-values for annotations
formatted_p_cluster <- paste0("p (Cluster) = ", format.pval(p_value_cluster, digits = 2))
formatted_p_trt <- paste0("p (Treatment) = ", format.pval(p_value_trt, digits = 2))
formatted_p_interaction <- paste0("p (Cluster:Treatment) = ", format.pval(p_value_interaction, digits = 2))

cluster <- ggplot(data4stats, aes(x = cluster, y = grazing, fill = cluster)) +
  geom_boxplot(alpha = 0.7,
    outlier.shape = NA,
    width = 0.5,
    position = position_dodge(0.5)) +
  geom_jitter(
    aes(fill = cluster, shape = phyto),
    size = 7,
    position = position_jitterdodge(jitter.width = 0.07, dodge.width = 0.7),
    alpha = 0.5, 
    stroke = 2,
    # shape = 21,
    color = "black"
  ) +
  labs(
    x = "SOM cluster",
    y = expression(bold(Grazing~(d^-1))),
    fill = "",
    color = "", 
    shape = ""
  ) +
   scale_fill_manual(values = pal2) +
  scale_color_manual(values = pal2) +
  scale_shape_manual(values = shape3) +
   theme_linedraw() +
  custom.theme +
  # Add p-value annotations for phyto and interaction
  annotate(
    "text",
    x = 1,
    y = max(data4stats$grazing, na.rm = TRUE),
    label = formatted_p_cluster,
    size = 8,  vjust = 2
  ) +
   guides(fill = "none") 


# Create an interaction plot for 'cluster' and 'trt2' as a box plot
interaction_plot <- ggplot(data4stats, aes(x = factor(trt2, levels = plot_levels), y = grazing)) +
 geom_boxplot(aes(fill = factor(trt, levels = plot_levels), color = factor(trt, levels = plot_levels)),
              alpha = 0.7,
              outlier.shape = NA,
    width = 0.5,
    position = position_dodge(0.5)) +
 geom_jitter(
    aes(fill = factor(trt, levels = plot_levels), shape = phyto),
    size = 7,
    # shape = 21, 
     position = position_jitterdodge(jitter.width = 0.07, dodge.width = 0.7),
    alpha = 0.5,
    stroke = 2,
    color = "black"
  ) +
  facet_wrap(~ cluster) +  # Facet by 'cluster' to see interactions per cluster
  labs(
    x = expression(bold(Treatment)),
    y = expression(bold(Grazing~(d^-1))),
    fill = "",
    color = "", 
    shape = ""
  ) +
  scale_fill_manual(values = pal4) +
  scale_color_manual(values = pal4) +
   scale_shape_manual(values = shape3) +
  theme_linedraw() +
  guides(color = "none") +
  custom.theme +
  # Add p-value annotations for cluster and interaction
  annotate(
    "text",
    x = 1.5,  # Position for p-value of interaction
    y = max(data4stats$grazing, na.rm = TRUE) * 0.95,
    label = formatted_p_interaction,
    size = 6, vjust = 2
  ) +
  annotate(
    "text",
    x = 1.5,
    y = max(data4stats$grazing, na.rm = TRUE) * 0.85,
    label = formatted_p_cluster,
    size = 6, vjust = 2
  ) +
  annotate(
    "text",
    x = 1.5,
    y = max(data4stats$grazing, na.rm = TRUE) * 0.75,
    label = formatted_p_trt,
    size = 6, vjust = 2
  )

grazing <- cluster + interaction_plot
```

```{r phyto accum model, fig.width=26, fig.asp = 0.8}
# Fit the ANOVA model with interaction
mod3 <- aov(accum ~ cluster * trt2, data = data4stats)

# Extract the ANOVA table
anova_results3 <- summary(mod3)

# Get p-values for significant terms
p_value_cluster <- anova_results3[[1]]["Pr(>F)"][1,1]
p_value_trt <- anova_results3[[1]]["Pr(>F)"][2,1]
# p_value_interaction <- anova_results2[[1]]["Pr(>F)"][3,1]

# Format p-values for annotations
formatted_p_cluster <- paste0("p (Cluster) = ", format.pval(p_value_cluster, digits = 2))
formatted_p_trt <- paste0("p (Treatment) = ", format.pval(p_value_trt, digits = 2))
# formatted_p_interaction <- paste0("p (cluster:trt) = ", format.pval(p_value_interaction, digits = 2))

cluster <- ggplot(data4stats, aes(x = factor(cluster, levels = plot_levels), y = accum, fill = cluster)) +
  geom_boxplot(alpha = 0.7,
    outlier.shape = NA,
    width = 0.4,
    position = position_dodge(0.5)) +
   geom_jitter(
    aes(fill = cluster, shape = phyto),
    size = 7,
    position = position_jitterdodge(jitter.width = 0.07, dodge.width = 0.7),
    alpha = 0.5, 
    stroke = 2,
    # shape = 21,
    color = "black"
  ) +
  labs(
    x = "SOM cluster",
    y = expression(bold(Accumulation~rate~(d^-1))),
    fill = "",
    color = "",
    shape = ""
  ) +
  scale_fill_manual(values = pal2) +
  scale_color_manual(values = pal2) +
   scale_shape_manual(values = shape3) +
   theme_linedraw() +
  custom.theme +
  annotate(
    "text",
    x = 1,
    y = max(data4stats$accum, na.rm = TRUE),
    label = formatted_p_cluster,
    size = 6,  vjust = 2
  ) +
   guides(color = "none", fill = "none") 


# Plot for Treatment Effect with ANOVA p-value using Box Plot
trt <-  ggplot(data4stats, aes(x = factor(trt2, levels = plot_levels), y = accum, fill = factor(trt, levels = plot_levels))) +
  geom_boxplot(alpha = 0.7,
    outlier.shape = NA,
    width = 0.4,
    position = position_dodge(0.5)) +
 geom_jitter(
    aes(fill = factor(trt, levels = plot_levels), shape = phyto),
    size = 7,
    position = position_jitterdodge(jitter.width = 0.07, dodge.width = 0.7),
    alpha = 0.5, 
    stroke = 2,
    # shape = 21,
    color = "black"
  ) +
  labs(
    x = "Treatment",
    y = expression(bold(Accumulation~rate~(d^-1))),
    fill = "",
    color = "",
    shape = ""
  ) +
  scale_fill_manual(values = pal4) +
  scale_color_manual(values = pal4) +
   scale_shape_manual(values = shape3) +
   theme_linedraw() +
  custom.theme +
  # Add p-value annotations for interaction
  annotate(
    "text",
    x = 1,
    y = max(data4stats$accum, na.rm = TRUE),
    label = formatted_p_trt,
    size = 6,  vjust = 2
  ) +
   guides(color= "none") 

# Combine plots side by side
accum <- cluster + trt +  plot_layout(guides = 'collect') & theme(legend.position = "top")

```

```{r fig5, fig.width=33, fig.asp = 1.4}
fig5 <- mu / (grazing +  guides(fill = "none", color = "none")) / (accum + guides(fill = "none", color = "none")) +
  plot_layout(guides = "collect") + plot_annotation(tag_levels = 'A')  &
  theme(plot.tag = element_text(size = 45), legend.position = "top", legend.box="vertical")

ggsave(fig4, file = "~/github/oceprf_smokeonthewater/prod/figs/phyto_rates.svg", width = 33, height = 46)
```


## Supplemental figures


```{r k v d plot, fig.width=50, fig.asp = 0.5}
kvd <- ggplot(rates %>% mutate(cluster = ifelse(cluster == "High biomass", "High~biomass", "Low~biomass")), aes(
  x = d,
  y = k,
  color = factor(trt, levels = plot_levels)
)) +
  geom_point(
    aes(shape = theory_violated, color = factor(trt, levels = plot_levels)),
    size = 8,
    alpha = 0.8
  ) +
  geom_smooth(
    method = lm,
    se = FALSE,
    linewidth = 1.1,
    alpha = 0.8
  ) +
  # facet_grid(
  #   # ggh4x::facet_nested_wrap(
  #   factor(phyto, levels = plot_levels) ~ factor(exp, levels = plot_levels),
  #   labeller = label_parsed,
  #   scales = "free"
  # ) +
  ggh4x::facet_nested(
    factor(phyto, levels = plot_levels)  ~  factor(cluster, levels = plot_levels) + exp,
    scales = "free_y",
    labeller = label_parsed
  ) +
  scale_color_manual(values = pal4) +
  scale_fill_manual(values = pal4) +
  scale_shape_manual(values = shape2a, guide = guide_legend(override.aes = list(fill = "black"))) +
  labs(
    color = "",
    y = expression(bold(Apparent ~ growth ~ rate ~ (d ^ -1))),
    x = expression(bold(Dilution)),
    shape = "Theory violated"
  ) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw() +
  custom.theme +
  theme(axis.text.x = element_text(angle = 45, size = 26, vjust = 0.1)) 

ggsave(kvd, file = "~/github/oceprf_smokeonthewater/prod/figs/division_v_dilution.svg", width = 48, height = 20)
```


```{r phyto PCA plot}

pca <- prcomp(data4stats[, -c(1,2,3,4,5, 12)],  scale = TRUE)

pca_plot <- fviz_pca_biplot(pca , 
                                  geom.ind = c("point"),
                                  # fill.ind = as_factor(round(data4stats$composite_z, 1)),
                                  fill.ind = data4stats$trt,
                                  pointshape = 21, pointsize=3,
                                  palette = "set2",labelsize = 5, col.var = "black",
                                  addEllipses=F, ellipse.level=0.90, mean.point =FALSE,
                                  repel = TRUE) +
  scale_fill_viridis_d(option = "H")+
  labs(fill = "Biomass Index", title = "") +
  theme_test() +
  theme(text = element_text(size = 12))

ggsave(pca_plot, file = "~/github/oceprf_smokeonthewater/prod/figs/pca.svg", width = 12, height = 8)
```


# Save data

```{r save data}
write_csv(rates, prod_path)
write_csv(bcodmo, bcodmo_path)
```


